name: data-science-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.2
  - numpy=1.24.2
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scipy=1.10.1
  - statsmodels=0.14.0
  - imbalanced-learn=0.10.1
  - joblib=1.3.1
  - jupyter=1.0.0
  - plotly=5.14.0
  - yellowbrick=1.5
